/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MEDIC;
import javax.swing.JOptionPane;
/**
 *
 * @author ITUNU
 */
public class TREAT extends javax.swing.JFrame {
    /**
     * Creates new form TREAT
     */
    public TREAT() {
        initComponents();
                setLocationRelativeTo(this);
        
    }
     public TREAT(String ID) {
        initComponents();
        nam.setText(ID);
         setLocationRelativeTo(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nam = new javax.swing.JTextField();
        elec = new javax.swing.JTextField();
        temp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BtnCHECK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rep = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BtnCHECK1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("buc");

        nam.setEditable(true);
        nam.setEnabled(true);
        nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namActionPerformed(evt);
            }
        });

        elec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elecActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Id: ");

        BtnCHECK.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BtnCHECK.setText("CHECK");
        BtnCHECK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCHECKActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Pulse: ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Body Temp. :");

        rep.setEditable(false);
        rep.setColumns(20);
        rep.setRows(5);
        rep.setEnabled(false);
        jScrollPane1.setViewportView(rep);

        jLabel7.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Report: ");

        BtnCHECK1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BtnCHECK1.setText("BACK");
        BtnCHECK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCHECK1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnCHECK))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(elec, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCHECK1)
                    .addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(BtnCHECK1)))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(elec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(BtnCHECK)
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elecActionPerformed

    private void BtnCHECKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCHECKActionPerformed
        // TODO add your handling code here:
       rep.setText("");
        String name= nam.getText();
        String bio_electric= elec.getText();
        String temperature= temp.getText();
        String report= rep.getText();
        String HY = rep.getText();
        medreport fit = new medreport (); 
        if (name.equals("") ) {
          JOptionPane.showMessageDialog(null, "supply your id");
        } else {
            //CHECK IF ID EXIST
            boolean avail=fit.checkID(name);
            if (avail==false){
                JOptionPane.showMessageDialog(null, "ID not Found");
            }else{
            if(bio_electric.equals("") ){
            JOptionPane.showMessageDialog(null, "supply your pulse reading");
             } else
                    if (temperature.equals("") ){
                        JOptionPane.showMessageDialog(null, "supply your blood pressure reading");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "all readings provided");
                    }
           
                        if (( Integer.parseInt(bio_electric) < 60) && ( Integer.parseInt(temperature) < 120/80)){
                        rep.setText("your blood pressure reading is low likewise your pulse rate,\n if any of the following symptoms is evident see a physician: shivering, mental confusion, weakness, difficulty in working/exercising, tiredness, shortness of breath, light headedness and passing out."
                               + "\n First aid include: warm drinks, warm clothings, staying active, control your cholesterol and blood pressure eat low fat and low salt diet,\n  get regular execise and quit smoking if you do."+HY);
                               // rep.setText(HY);
    }else
                        if(( Integer.parseInt(bio_electric) > 60) && (Integer.parseInt(temperature) > 120/80)){
                                rep.setText("your pulse reading and blood pressure reading are on the high side, \n symptoms nclude: dizziness, shortness of breath, lightheadedness,"
                                + "rapid pulse rate, heart palpitation, chest pain, poor appetite, sore throat, cough, ear pain, diarrhea, fussiness and fainting \n try the following first aid then visit a physician: try to be calm,"
                                + "stay away from chocolate, tobacco products, coffee, tea, alcohol, avoid illegal use of drugs, \n avoid medications that act like stimulants, take drugs such as acetaminophen and ibuprofen as prescibed by the label, bathing in lukewarm water, wear light clothes or cover and drink plenty of fluids."+HY);
                         //rep.setText(HY);
                    }
                        else
                            if((Integer.parseInt(bio_electric) < 60) && (Integer.parseInt(temperature) > 120/80)){
                              rep.setText("your pulse rate is low, \n your blood pressure is on the high side \n symptoms include:weakness, difficulty in working/exercising, tiredness, shortness of breath, light headedness, passing out, \n chest pain, poor appetite, sore throat, cough, ear pain, diarrhea and fussiness. "
                                        + "\n First aid include:control your cholesterol and blood pressure eat low fat and low salt diet,\n  get regular execise and quit smoking if you do "
                                        + "\n take drugs such as acetaminophen and ibuprofen as prescibed by the label, bathing in lukewarm water, wear light clothes or cover and drink plenty of fluids."+HY);
                               // rep.setText(HY);      
                            }else
                                if((Integer.parseInt(bio_electric) > 60) &&(Integer.parseInt(temperature) < 120/80)){
                                     rep.setText( "your pulse rate is high, while your blood pressure is low. \n Symptoms are: dizziness, shortness of breath, lightheadedness,rapid pulse rate, heart palpitation, shivering and mental confusion. "
                                            + "\n First aid include: try to be calm,"
                                + "stay away from chocolate, tobacco products, coffee, tea, alcohol, avoid illegal use of drugs, \n avoid medications that act like stimulants, warm drinks, warm clothings and endeavour to stay active."+HY);
                                    //rep.setText(HY);
                                }
                                else{
                        rep.setText("you have a normal pulse rate and blood pressure; \n try to maintain a healthy lifestyle. eat and drink fluids well."+HY);
                    //rep.setText(HY);
    }
                     
                    fit.medreport( name, bio_electric, temperature, rep.getText());
            }
                    //rep.setText(HY);
        }
    }//GEN-LAST:event_BtnCHECKActionPerformed

    private void BtnCHECK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCHECK1ActionPerformed
        // TODO add your handling code here:
         choice pre= new choice();
        pre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCHECK1ActionPerformed

    private void namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TREAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TREAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TREAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TREAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
/* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                new TREAT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCHECK;
    private javax.swing.JButton BtnCHECK1;
    private javax.swing.JTextField elec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nam;
    private javax.swing.JTextArea rep;
    private javax.swing.JTextField temp;
    // End of variables declaration//GEN-END:variables
}
